// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: transactions.sql

package sqlc

import (
	"context"
	"time"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id,
    amount,
    description,
    transaction_type,
    category,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?6
) RETURNING id, user_id, amount, description, transaction_type, created_at, updated_at, category
`

type CreateTransactionParams struct {
	UserID          int64     `db:"user_id" json:"user_id"`
	Amount          int64     `db:"amount" json:"amount"`
	Description     string    `db:"description" json:"description"`
	TransactionType int64     `db:"transaction_type" json:"transaction_type"`
	Category        *string   `db:"category" json:"category"`
	Date            time.Time `db:"date" json:"date"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg *CreateTransactionParams) (*Transactions, error) {
	row := q.queryRow(ctx, q.createTransactionStmt, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Description,
		arg.TransactionType,
		arg.Category,
		arg.Date,
	)
	var i Transactions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Description,
		&i.TransactionType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
	)
	return &i, err
}

const deleteTransactionByIDAndUserID = `-- name: DeleteTransactionByIDAndUserID :exec
DELETE FROM transactions WHERE id = ?1 AND user_id = ?2
`

type DeleteTransactionByIDAndUserIDParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteTransactionByIDAndUserID(ctx context.Context, arg *DeleteTransactionByIDAndUserIDParams) error {
	_, err := q.exec(ctx, q.deleteTransactionByIDAndUserIDStmt, deleteTransactionByIDAndUserID, arg.ID, arg.UserID)
	return err
}

const getLatestTransactionsByUserID = `-- name: GetLatestTransactionsByUserID :many
SELECT id, user_id, amount, description, transaction_type, created_at, updated_at, category FROM transactions WHERE user_id = ?1 ORDER BY updated_at DESC
`

func (q *Queries) GetLatestTransactionsByUserID(ctx context.Context, userID int64) ([]*Transactions, error) {
	rows, err := q.query(ctx, q.getLatestTransactionsByUserIDStmt, getLatestTransactionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Transactions{}
	for rows.Next() {
		var i Transactions
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Description,
			&i.TransactionType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestTransactionsByUserIDAndTransactionType = `-- name: GetLatestTransactionsByUserIDAndTransactionType :many
SELECT id, user_id, amount, description, transaction_type, created_at, updated_at, category FROM transactions WHERE user_id = ?1 AND transaction_type = ?2 ORDER BY updated_at DESC
`

type GetLatestTransactionsByUserIDAndTransactionTypeParams struct {
	UserID          int64 `db:"user_id" json:"user_id"`
	TransactionType int64 `db:"transaction_type" json:"transaction_type"`
}

func (q *Queries) GetLatestTransactionsByUserIDAndTransactionType(ctx context.Context, arg *GetLatestTransactionsByUserIDAndTransactionTypeParams) ([]*Transactions, error) {
	rows, err := q.query(ctx, q.getLatestTransactionsByUserIDAndTransactionTypeStmt, getLatestTransactionsByUserIDAndTransactionType, arg.UserID, arg.TransactionType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Transactions{}
	for rows.Next() {
		var i Transactions
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Description,
			&i.TransactionType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalTransactionsByUserIDAndTransactionTypeForLastMonth = `-- name: GetTotalTransactionsByUserIDAndTransactionTypeForLastMonth :one
SELECT SUM(amount) FROM transactions WHERE user_id = ?1 AND transaction_type = ?2 AND strftime('%Y-%m', created_at) = strftime('%Y-%m', 'now', '-1 month') ORDER BY updated_at DESC
`

type GetTotalTransactionsByUserIDAndTransactionTypeForLastMonthParams struct {
	UserID          int64 `db:"user_id" json:"user_id"`
	TransactionType int64 `db:"transaction_type" json:"transaction_type"`
}

func (q *Queries) GetTotalTransactionsByUserIDAndTransactionTypeForLastMonth(ctx context.Context, arg *GetTotalTransactionsByUserIDAndTransactionTypeForLastMonthParams) (*float64, error) {
	row := q.queryRow(ctx, q.getTotalTransactionsByUserIDAndTransactionTypeForLastMonthStmt, getTotalTransactionsByUserIDAndTransactionTypeForLastMonth, arg.UserID, arg.TransactionType)
	var sum *float64
	err := row.Scan(&sum)
	return sum, err
}

const getTotalTransactionsByUserIDAndTransactionTypeForThisMonth = `-- name: GetTotalTransactionsByUserIDAndTransactionTypeForThisMonth :one
SELECT SUM(amount) FROM transactions WHERE user_id = ?1 AND transaction_type = ?2 AND strftime('%Y-%m', created_at) = strftime('%Y-%m', 'now') ORDER BY updated_at DESC
`

type GetTotalTransactionsByUserIDAndTransactionTypeForThisMonthParams struct {
	UserID          int64 `db:"user_id" json:"user_id"`
	TransactionType int64 `db:"transaction_type" json:"transaction_type"`
}

func (q *Queries) GetTotalTransactionsByUserIDAndTransactionTypeForThisMonth(ctx context.Context, arg *GetTotalTransactionsByUserIDAndTransactionTypeForThisMonthParams) (*float64, error) {
	row := q.queryRow(ctx, q.getTotalTransactionsByUserIDAndTransactionTypeForThisMonthStmt, getTotalTransactionsByUserIDAndTransactionTypeForThisMonth, arg.UserID, arg.TransactionType)
	var sum *float64
	err := row.Scan(&sum)
	return sum, err
}

const getTotalTransactionsThisYearByUserIDAndTransactionType = `-- name: GetTotalTransactionsThisYearByUserIDAndTransactionType :one
SELECT SUM(amount) FROM transactions WHERE user_id = ?1 AND transaction_type = ?2 AND strftime('%Y', created_at) = strftime('%Y', 'now') ORDER BY updated_at DESC
`

type GetTotalTransactionsThisYearByUserIDAndTransactionTypeParams struct {
	UserID          int64 `db:"user_id" json:"user_id"`
	TransactionType int64 `db:"transaction_type" json:"transaction_type"`
}

func (q *Queries) GetTotalTransactionsThisYearByUserIDAndTransactionType(ctx context.Context, arg *GetTotalTransactionsThisYearByUserIDAndTransactionTypeParams) (*float64, error) {
	row := q.queryRow(ctx, q.getTotalTransactionsThisYearByUserIDAndTransactionTypeStmt, getTotalTransactionsThisYearByUserIDAndTransactionType, arg.UserID, arg.TransactionType)
	var sum *float64
	err := row.Scan(&sum)
	return sum, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, user_id, amount, description, transaction_type, created_at, updated_at, category FROM transactions WHERE id = ?1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id int64) (*Transactions, error) {
	row := q.queryRow(ctx, q.getTransactionByIDStmt, getTransactionByID, id)
	var i Transactions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Description,
		&i.TransactionType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
	)
	return &i, err
}

const getTransactionsByUserID = `-- name: GetTransactionsByUserID :many
SELECT id, user_id, amount, description, transaction_type, created_at, updated_at, category FROM transactions WHERE user_id = ?1
`

func (q *Queries) GetTransactionsByUserID(ctx context.Context, userID int64) ([]*Transactions, error) {
	rows, err := q.query(ctx, q.getTransactionsByUserIDStmt, getTransactionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Transactions{}
	for rows.Next() {
		var i Transactions
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Description,
			&i.TransactionType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByUserIDAndTransactionType = `-- name: GetTransactionsByUserIDAndTransactionType :many
SELECT id, user_id, amount, description, transaction_type, created_at, updated_at, category FROM transactions WHERE user_id = ?1 AND transaction_type = ?2
`

type GetTransactionsByUserIDAndTransactionTypeParams struct {
	UserID          int64 `db:"user_id" json:"user_id"`
	TransactionType int64 `db:"transaction_type" json:"transaction_type"`
}

func (q *Queries) GetTransactionsByUserIDAndTransactionType(ctx context.Context, arg *GetTransactionsByUserIDAndTransactionTypeParams) ([]*Transactions, error) {
	rows, err := q.query(ctx, q.getTransactionsByUserIDAndTransactionTypeStmt, getTransactionsByUserIDAndTransactionType, arg.UserID, arg.TransactionType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Transactions{}
	for rows.Next() {
		var i Transactions
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Description,
			&i.TransactionType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsCountByUserIDAndTransactionType = `-- name: GetTransactionsCountByUserIDAndTransactionType :one
SELECT COUNT(*) FROM transactions WHERE user_id = ?1 AND transaction_type = ?2
`

type GetTransactionsCountByUserIDAndTransactionTypeParams struct {
	UserID          int64 `db:"user_id" json:"user_id"`
	TransactionType int64 `db:"transaction_type" json:"transaction_type"`
}

func (q *Queries) GetTransactionsCountByUserIDAndTransactionType(ctx context.Context, arg *GetTransactionsCountByUserIDAndTransactionTypeParams) (int64, error) {
	row := q.queryRow(ctx, q.getTransactionsCountByUserIDAndTransactionTypeStmt, getTransactionsCountByUserIDAndTransactionType, arg.UserID, arg.TransactionType)
	var count int64
	err := row.Scan(&count)
	return count, err
}
